import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import React from "react"
import { cn } from "@/lib/utils"
import { Providers } from "@/app/providers"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout(
  props: Readonly<{
    children: React.ReactNode
    params?: {
      lang?: string
    }
  }>,
) {
  return (
    <html lang={props.params?.lang ?? "en"} className="h-[100svh]">
      <body className={cn(inter.className, "h-full")}>
        <Providers>{props.children}</Providers>
      </body>
    </html>
  )
}
